# -*- mode: ruby -*-
#################################################################################
# Configurable Parameters
VM_MEMORY_MB = 2048 # Default is 5120MB 
VM_CPU_CORES = 3
#################################################################################

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64" # The OS is Ubuntu 14.04 64 bits
  config.vm.hostname = "mdmsandbox.totvs.com"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-sandbox"
    vb.customize ["modifyvm", :id, "--memory", VM_MEMORY_MB, "--cpus", VM_CPU_CORES]
  end

  # host-only network
  config.vm.network :private_network, ip: "192.168.50.10"

  config.vm.provision "shell", inline: <<-SHELL
      rm -rf /var/lib/apt/lists/*
      apt-get -y update
      which curl 1>/dev/null 2>/dev/null || sudo apt-get install -y curl
      curl -L https://raw.githubusercontent.com/TOTVS/mdmpublic/master/test/bootstrap_mdm_sandbox.sh | bash -e
  SHELL
end
