# -*- mode: ruby -*-
#################################################################################
# Configurable Parameters
VM_MEMORY_MB = 5120

VM_HOSTNAME_NAME = "mdmsandbox.totvs.com"

#################################################################################

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64" # The OS is Ubuntu 14.04 64 bits
  config.vm.provider :virtualbox do |vb|
    vb.name = "vagrant-mdm-sandbox"
    vb.customize ["modifyvm", :id, "--memory", VM_MEMORY_MB, "--cpus", "2"]
  end

  config.vm.hostname = VM_HOSTNAME_NAME
  # config.ssh.username = "root"
  # config.ssh.private_key_path = "~/vagrant_private_key"

  # host-only network
  config.vm.network :private_network, ip: "192.168.50.10"

  # config.vm.synced_folder "~/vagrant", "/root/vagrant", owner: "root", group: "root"

  config.vm.provision "shell", inline: <<-SHELL
      which curl 1>/dev/null 2>/dev/null || sudo apt-get install -y curl
      curl -L https://raw.githubusercontent.com/TOTVS/mdmpublic/master/test/bootstrap_mdm_sandbox.sh | bash -e
  SHELL
end
